// todo-app-angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { Todo } from './models/Todo';
import { StorageService } from './storage.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  todos: Array<Todo>;
  filterType = 'All';
  todoText = '';

  constructor(private readonly storageService: StorageService) {
    this.todos = this.storageService.getTodos();
  }

  toggleComplete(todo: Todo): void {
    todo.isCompleted = !todo.isCompleted;
    this.storageService.saveTodos(this.todos);
  }

  addTodo(event: any): void {
    event.preventDefault();

    if (this.todoText) {
      const newId = this.todos.length > 0 ? 1 : Math.max(...this.todos.map(t => t.id)) + 1;
      const todo = { id: newId, text: this.todoText, isCompleted: false };

      this.todos.push(todo);
      this.todoText = '';
      this.toggleFilterType('All');
      this.storageService.saveTodos(this.todos);
    }
  }

  deleteTodo(todo: Todo): void {
    const todoIndex = this.todos.findIndex(t => t.id === todo.id);
    this.todos.splice(todoIndex, 1);
    this.storageService.saveTodos(this.todos);
  }

  deleteAllCompleted(): void {
    this.todos = this.todos.filter(t => !t.isCompleted);
    this.storageService.saveTodos(this.todos);
  }

  toggleFilterType(filterType: string): void {
    this.filterType = filterType;
  }

  isFilterType(filterType: string): boolean {
    return this.filterType === filterType;
  }

  get numberOfTodos(): number {
    return this.filteredTodos ? this.filteredTodos.length : 0;
  }

  get filteredTodos(): Array<Todo> {
    if (!this.todos) {
      return [];
    }

    const filterPredicate: (todo: Todo) => boolean = 
      this.filterType === 'All' ? () => true : 
      this.filterType === 'Active' ? (t) => !t.isCompleted :
      (t) => t.isCompleted;

    return this.todos.filter(filterPredicate);
  }
}

<main>
  <header>
    <h1>Todo</h1>
    <img id="languageLogo" src="assets/images/languageLogo.svg" alt="Angular Logo" />
  </header>
  <form (submit)="addTodo($event)">
    <input type="text" name="todoText" [(ngModel)]="todoText" placeholder="Create a new todo..." value="" />
    <button type="submit" id="createTodo">+</button>
  </form>
  <div id="todoList">
    <div id="todoListHeader">
      <span>{{ numberOfTodos }} items left</span>
      <ul id="todoFilters">
        <li [class.active]="isFilterType('All')">
          <button (click)="toggleFilterType('All')">All</button>
        </li>
        <li [class.active]="isFilterType('Active')">
          <button (click)="toggleFilterType('Active')">Active</button>
        </li>
        <li [class.active]="isFilterType('Completed')">
          <button (click)="toggleFilterType('Completed')">Completed</button>            
        </li>
      </ul>
      <button id="clearCompleted" (click)="deleteAllCompleted()">Clear Completed</button>
    </div>
    <ul id="todoListBody">
      <li *ngFor="let todo of filteredTodos" [class.checked]="todo.isCompleted">
        <button class="todoStatus" (click)="toggleComplete(todo)">&#10003;</button>
        <span class="todoText" (click)="toggleComplete(todo)">{{ todo.text }}</span>
        <button class="removeTodo" (click)="deleteTodo(todo)">
          <img class="deleteLogo" src="assets/images/deleteTodoLogo.svg" alt="Delete Todo" />
        </button>
      </li>      
    </ul>
  </div>
</main>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>

// todo-app-react/src/App.js
import { useState } from 'react';

import './App.css';

const defaultTodos = JSON.parse(localStorage.getItem('ld-react-todos')) || [
  { id: 1, text: 'Complete the React.js todo app', isCompleted: false },
  { id: 2, text: 'Complete the Angular todo app', isCompleted: false },
  { id: 3, text: 'Complete the Vue.js todo app', isCompleted: false }
];

const defaultFilterType = localStorage.getItem('ld-react-filterType') || 'All';
const allFilterPredicate = (todos) => todos;
const activeFilterPredicate = (todos) => !todos.isCompleted;
const completedFilterPredicate = (todos) => todos.isCompleted;

function App() {
  const [todos, setTodos] = useState(defaultTodos);
  const [filterType, setFilterType] = useState(defaultFilterType);
  const currentFilterPredicate = 
        filterType === 'All' ? allFilterPredicate :
        filterType === 'Active' ? activeFilterPredicate : 
        completedFilterPredicate;
  const filteredTodos = todos.filter(currentFilterPredicate);
  const [todoText, setTodoText] = useState('');

  const toggleComplete = (todoId) => {
    setTodos((prevTodos) => {      
      const newTodos = [...prevTodos];
      const existingTodoIndex = prevTodos.findIndex(t => t.id === todoId);

      if (existingTodoIndex >= 0) {
        newTodos[existingTodoIndex] = { 
          ...prevTodos[existingTodoIndex],
          isCompleted: !prevTodos[existingTodoIndex].isCompleted
        };
      }

      localStorage.setItem('ld-react-todos', JSON.stringify(newTodos))

      return newTodos;
    });
  };

  const toggleFilterType = (filterType) => {
    localStorage.setItem('ld-react-filterType', filterType);
    setFilterType(filterType);
  };

  const addTodo = (e) => {
    e.preventDefault();

    if (todoText) {
      setTodos(prevTodos => {
        const newId = prevTodos.length === 0 ? 1 : Math.max(...prevTodos.map(t => t.id)) + 1;
        const todo = { id: newId, text: todoText, isCompleted: false };
  
        const newTodos = [...prevTodos, todo];        
        localStorage.setItem('ld-react-todos', JSON.stringify(newTodos));

        return newTodos;
      });

      setTodoText('');
      setFilterType('All');
    }
  };

  const deleteTodo = (todoId) => {
    setTodos(prevTodos => {
      const newTodos = prevTodos.filter(t => t.id !== todoId);
      localStorage.setItem('ld-react-todos', JSON.stringify(newTodos))

      return newTodos;
    });
  }

  const deleteAllCompleted = () => {
    setTodos(prevTodos => {
      const newTodos = prevTodos.filter(t => !t.isCompleted);
      localStorage.setItem('ld-react-todos', JSON.stringify(newTodos))

      return newTodos;
    });
  };

  const todoItemsEl = filteredTodos.map((t, i) => {
    const checkClassName = !t.isCompleted ? null : 'checked';
    
    return (
      <li key={i} className={checkClassName}>
        <button className="todoStatus" onClick={ () => toggleComplete(t.id) }>&#10003;</button>
        <span className="todoText" onClick={ () => toggleComplete(t.id) }>{ t.text }</span>
        <button className="removeTodo" onClick={ () => deleteTodo(t.id) }>
          <img className="deleteLogo" src="images/deleteTodoLogo.svg" alt="Delete Todo" />
        </button>
      </li>
    )
  });

  return (
    <main>
        <header>
          <h1>Todo</h1>
          <img id="languageLogo" src="images/languageLogo.svg" alt="React Logo" />
        </header>
        <form onSubmit={addTodo}>
          <input type="text" placeholder="Create a new todo..." onChange={(e) => setTodoText(e.target.value)} value={todoText} />
          <button type="submit" id="createTodo">+</button>
        </form>
        <div id="todoList">
          <div id="todoListHeader">
            <span>{ filteredTodos.length } items left</span>
            <ul id="todoFilters">
              <li className={ filterType === 'All' ? 'active': null }>
                <button onClick={ () => toggleFilterType('All')}>All</button>
              </li>
              <li className={ filterType === 'Active' ? 'active': null }>
                <button onClick={ () => toggleFilterType('Active')}>Active</button>
              </li>
              <li className={ filterType === 'Completed' ? 'active': null }>
                <button onClick={ () => toggleFilterType('Completed')}>Completed</button>            
              </li>
            </ul>
            <button id="clearCompleted" onClick={deleteAllCompleted}>Clear Completed</button>
          </div>
          <ul id="todoListBody">
            { todoItemsEl }
          </ul>
        </div>
      </main>
  );
}

export default App;
